version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend:
        patterns: ["*"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: nuget
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      backend:
        patterns: ["*"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
