<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1d03c7b3-ad57-43ad-8098-564c1b9bb0d4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECAbogados.Application\ECAbogados.Application.csproj" />
    <ProjectReference Include="..\ECAbogados.Infrastructure\ECAbogados.Infrastructure.csproj" />
  </ItemGroup>

</Project>
